-- LINK : https://en.wikibooks.org/wiki/SQL_Exercises/Employee_management
-- 2.1 Sélectionnez le nom de famille de tous les employés.
-- 2.2 Sélectionnez le nom de famille de tous les employés, sans doublons.
-- 2.3 Sélectionnez toutes les données des employés dont le nom de famille est "Smith".
-- 2.4 Sélectionnez toutes les données des employés dont le nom de famille est "Smith" ou "Doe".
-- 2.5 Sélectionnez toutes les données des employés qui travaillent dans le département 14.
-- 2.6 Sélectionnez toutes les données des employés qui travaillent dans le département 37 ou le département 77.
-- 2.7 Sélectionnez toutes les données des employés dont le nom de famille commence par un "S".
-- 2.8 Sélectionnez la somme de tous les budgets des départements.
-- 2.9 Sélectionnez le nombre d'employés dans chaque département (vous n'avez qu'à indiquer le code du département et le nombre d'employés).
-- 2.10 Sélectionnez toutes les données des employés, y compris les données du service de chaque employé.
-- 2.11 Sélectionnez le nom et le prénom de chaque employé, ainsi que le nom et le budget du service de l'employé.
-- 2.12 Sélectionnez le nom et le nom de famille des employés travaillant pour les services dont le budget est supérieur à 60 000 $.
-- 2.13 Sélectionnez les départements dont le budget est supérieur au budget moyen de tous les départements.
-- 2.14 Sélectionnez les noms des départements comptant plus de deux employés.
-- 2.15 Très important - Sélectionnez le nom et le prénom des employés travaillant pour les départements avec le deuxième budget le plus bas.
-- 2.16 Ajouter un nouveau département appelé "Assurance qualité", avec un budget de 40 000 $ et le code départemental 11.
-- Et ajoutez un employé appelé "Mary Moore" dans ce département, avec le SSN 847-21-9811.
-- 2.17 Réduire le budget de tous les départements de 10 %.
-- 2.18 Réaffecter tous les employés du service Recherche (code 77) au service informatique (code 14).
-- 2.19 Supprimer du tableau tous les employés du service informatique (code 14).
-- 2.20 Supprimer du tableau tous les employés qui travaillent dans des services dont le budget est supérieur ou égal à 60 000 $.
-- 2.21 Supprimer du tableau tous les employés.
