-- LINK: https://en.wikibooks.org/wiki/SQL_Exercises/The_computer_store
-- 1.1 Sélectionnez les noms de tous les produits du magasin.
-- 1.2 Sélectionnez les noms et les prix de tous les produits du magasin.
-- 1.3 Sélectionnez le nom des produits dont le prix est inférieur ou égal à 200 $.
-- 1.4 Sélectionnez tous les produits dont le prix se situe entre 60 $ et 120 $.
-- 1.5 Sélectionnez le nom et le prix en centimes (c'est-à-dire que le prix doit être multiplié par 100).
-- 1.6 Calculer le prix moyen de tous les produits.
-- 1.7 Calculer le prix moyen de tous les produits dont le code fabricant est égal à 2.
-- 1.8 Calculer le nombre de produits dont le prix est supérieur ou égal à 180 $.
-- 1.9 Sélectionnez le nom et le prix de tous les produits dont le prix est supérieur ou égal à 180 $, et triez d'abord par prix (par ordre décroissant), puis par nom (par ordre croissant).
-- 1.10 Sélectionnez toutes les données des produits, y compris toutes les données du fabricant de chaque produit.
-- 1.11 Sélectionnez le nom du produit, le prix et le nom du fabricant de tous les produits.
-- 1.12 Sélectionnez le prix moyen des produits de chaque manufacturier en n'indiquant que le code du manufacturier.
-- 1.13 Sélectionnez le prix moyen des produits de chaque fabricant, en indiquant le nom du fabricant.
-- 1.14 Sélectionnez les noms de fabricants dont les produits ont un prix moyen supérieur ou égal à 150 $.
-- 1.15 Sélectionnez le nom et le prix du produit le moins cher.
-- 1.16 Sélectionnez le nom de chaque fabricant ainsi que le nom et le prix de son produit le plus cher.
-- 1.17 Ajouter un nouveau produit : Haut-parleurs, 70 $, fabricant 2.
-- 1.18 Mettez à jour le nom du produit 8 en "Imprimante laser".
-- 1.19 Appliquer une remise de 10% sur tous les produits.
-- 1.20 Appliquez une remise de 10 % sur tous les produits dont le prix est supérieur ou égal à 120 $.
